-- Create a new database called 'DOE_DB'
-- Connect to the 'master' database to run this snippet
CREATE DATABASE IF NOT EXISTS DOE_DB;
USE DOE_DB;

-- DROP DB
DROP DATABASE DOE_DB;


-- SCRIPTS TABLE: USER
-- TABLE 'USER'
CREATE TABLE `USER` (
    ID_USER INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    `PASSWORD` VARCHAR(100) NOT NULL,
    URL_PROFILE_IMAGE VARCHAR(255) DEFAULT '/path/to/default_profile_pic',
    PRIMARY KEY(ID_USER)
);

-- SCRIPTS TABLE: ORGANIZATION
-- TABLE 'ORGANIZATION'
CREATE TABLE `ORGANIZATION` (
    ID_ORGANIZATION INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(100),
    DESC_ORGANIZATION VARCHAR(100),
    CNPJ VARCHAR(14) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    FONE VARCHAR(100) NOT NULL,
	URI_PROFILE_IMAGE VARCHAR(255) DEFAULT '/path/to/default_ong_pic',
	PRIMARY KEY(ID_ORGANIZATION)
);




-- ==========MUDAR "DONATION" <====> "PUBLICATION"=================


-- SCRIPTS TABLE: DONATION
-- TABLE 'DONATION'
CREATE TABLE `DONATION` (
	ID_DONATION INTEGER NOT NULL AUTO_INCREMENT,
	ID_USER INTEGER NOT NULL,
    ID_DONATION_ITEM INTEGER NOT NULL,
    PRIMARY KEY(ID_DONATION),
    CONSTRAINT FK_DONATION_USER FOREIGN KEY(ID_USER) REFERENCES `USER`(ID_USER)
);


-- SCRIPTS TABLE: DONATION_LIST
-- TABLE 'DONATION_LIST'
CREATE TABLE `DONATION_LIST` (
    ID_DONATION_LIST INTEGER AUTO_INCREMENT NOT NULL,
    `NAME` VARCHAR(100) NOT NULL,
    ID_ORGANIZATION INTEGER NOT NULL,
    ID_DONATION_LIST_PROGRESS INTEGER NOT NULL,
    ID_DONATION_ITEM INTEGER NOT NULL,
    PRIMARY KEY(ID_DONATION_LIST),
    CONSTRAINT FK_DONATION_LIST_ORGANIZATION FOREIGN KEY(ID_ORGANIZATION) REFERENCES ORGANIZATION(ID_ORGANIZATION),
    CONSTRAINT FK_DONATION_LIST_DONATION_PROGRESS FOREIGN KEY(ID_DONATION_LIST_PROGRESS) REFERENCES DONATION_PROGRESS(ID_DONATION_PROGRESS),
    CONSTRAINT FK_DONATION_LIST_DONATION_ITEM FOREIGN KEY(ID_DONATION_ITEM) REFERENCES DONATION_ITEM(ID_DONATION_ITEM)
);

-- TABLE 'DONATION_PROGRESS'
CREATE TABLE `DONATION_LIST_PROGRESS` (
    ID_DONATION_PROGRESS INTEGER AUTO_INCREMENT NOT NULL,
	`TYPE` ENUM('FAIL', 'DOING', 'DONE'),
    PRIMARY KEY(ID_DONATION_PROGRESS)
);

-- TABLE 'DONATION_ITEM'
CREATE TABLE `DONATION_LIST_ITEM` (
    ID_DONATION_LIST_ITEM INTEGER AUTO_INCREMENT NOT NULL,
    `NAME` VARCHAR(100) NOT NULL,
    CATEGORY ENUM('VESTIMENTA', 'ALIMENTO', 'SAÚDE', 'HIGIENE'),
    AVALIABLE CHAR(1) NOT NULL DEFAULT 'Y',
    PRIMARY KEY(ID_DONATION_ITEM),
    CONSTRAINT CHK_DONATION_LIST_ITEM CHECK (AVALIABLE = 'Y' OR AVALIABLE = 'N')
);
